
import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ChevronDown, ChevronUp, Send, Loader2 } from 'lucide-react';
import { getChatMessages, sendChatMessage } from '@/lib/chatService';
import { useAuth } from '@/contexts/AuthContext';

interface Message {
  id: string;
  sender: string;
  recipient: string;
  message: string;
  timestamp: string;
  context_id: string;
}

const UniversalChat: React.FC = () => {
  const { user } = useAuth();
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [contextId, setContextId] = useState('universal-context');
  const [loading, setLoading] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  // Load messages for the current context
  useEffect(() => {
    const loadMessages = async () => {
      try {
        setLoading(true);
        const { data, error } = await getChatMessages(contextId);
        if (error) throw error;
        if (data) setMessages(data);
      } catch (error) {
        console.error('Error loading messages:', error);
      } finally {
        setLoading(false);
      }
    };
    
    loadMessages();
  }, [contextId]);
  
  // Scroll to bottom of message container when messages update
  useEffect(() => {
    if (isExpanded) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isExpanded]);
  
  const handleSendMessage = async () => {
    if (!newMessage.trim()) return;
    
    setLoading(true);
    try {
      const { data, error } = await sendChatMessage({
        sender: 'Leader',
        recipient: 'Pilot',
        message: newMessage,
        context_id: contextId
      });
      
      if (error) throw error;
      
      if (data) {
        // Update the local state with the new message
        setMessages(prev => [...prev, data]);
        setNewMessage('');
        
        // Simulate an AI response after a short delay for demo purposes
        setTimeout(async () => {
          const aiResponse = await sendChatMessage({
            sender: 'Pilot',
            recipient: 'Leader',
            message: `I've received your message. As this is a demonstration, I'm providing an automated response. In a full implementation, responses would be generated by the AI.`,
            context_id: contextId
          });
          
          if (aiResponse.data) {
            setMessages(prev => [...prev, aiResponse.data]);
          }
        }, 1500);
      }
    } catch (error) {
      console.error('Error sending message:', error);
    } finally {
      setLoading(false);
    }
  };
  
  // Render message bubbles based on sender
  const renderMessage = (message: Message) => {
    const isLeader = message.sender === 'Leader';
    
    return (
      <div 
        key={message.id} 
        className={`flex ${isLeader ? 'justify-end' : 'justify-start'} mb-4`}
      >
        <div 
          className={`rounded-lg px-4 py-2 max-w-[80%] ${
            isLeader 
              ? 'bg-pilot-600 text-white' 
              : 'bg-gray-100 dark:bg-gray-800 text-foreground'
          }`}
        >
          <div className="text-sm font-medium mb-1">{message.sender}</div>
          <div className="whitespace-pre-wrap">{message.message}</div>
          <div className="text-xs mt-1 opacity-70">
            {new Date(message.timestamp).toLocaleTimeString()}
          </div>
        </div>
      </div>
    );
  };
  
  return (
    <div className="fixed bottom-0 right-2 z-10 w-96">
      <Card className={`shadow-lg transition-all ${isExpanded ? 'h-[500px]' : 'h-14'}`}>
        <div 
          className="h-14 flex items-center justify-between px-4 cursor-pointer border-b"
          onClick={() => setIsExpanded(!isExpanded)}
        >
          <div className="font-medium flex items-center gap-2">
            {loading && isExpanded && <Loader2 className="h-4 w-4 animate-spin" />}
            Universal Chat
          </div>
          <Button variant="ghost" size="sm">
            {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronUp className="h-4 w-4" />}
          </Button>
        </div>
        
        {isExpanded && (
          <>
            <CardContent className="overflow-y-auto h-[calc(100%-7rem)] p-4">
              {messages.length === 0 ? (
                <div className="text-center text-muted-foreground h-full flex items-center justify-center">
                  No messages yet. Start the conversation!
                </div>
              ) : (
                <div className="space-y-4">
                  {messages.map(renderMessage)}
                  <div ref={messagesEndRef} />
                </div>
              )}
            </CardContent>
            
            <CardFooter className="pt-2 pb-4 px-4">
              <div className="flex w-full gap-2">
                <Input
                  value={newMessage}
                  onChange={(e) => setNewMessage(e.target.value)}
                  placeholder="Type your message..."
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSendMessage();
                    }
                  }}
                  disabled={loading}
                />
                <Button 
                  onClick={handleSendMessage} 
                  disabled={loading || !newMessage.trim()}
                  className="flex gap-2 items-center"
                  size="sm"
                >
                  {loading ? <Loader2 className="animate-spin" size={16} /> : <Send size={16} />}
                </Button>
              </div>
            </CardFooter>
          </>
        )}
      </Card>
    </div>
  );
};

export default UniversalChat;
